export const CONFIG_COMMANDS=Object.freeze(['viewconfig','showconfig','showvars','viewvars','listvars','listconfig']);

// Descriptions enrich the command registry; they never decide which settings exist.
// Browser-owned settings may supply their own name and description alongside get/set.
const DETAILS=Object.freeze({
  game_mode:['Campaign variant','20: default compact campaign; 50: original campaign, console only. Changing mode returns to the title and resets mode thresholds; existing save is kept. New runs use the selected mode; Continue uses its saved mode. Session only.'],
  panic:['Allow Panic button','Enable emergency return of surviving cells to the start of the furthest physically reached leg. Also requests normal Recouple for existing fragments. Optional panic_penalty is off by default. Saved boolean, on by default.'],
  panic_penalty:['Panic score penalty enabled','Deduct panic_score_penalty_percent from the current run score once per successful rescue. All-time records stay unchanged. Off by default. Session only.'],
  panic_show_inactive:['Show Panic while safe','Keep the Panic circle visible throughout normal play. Off: show after the outside delay or immediately on overheating. Keyboard/controller activation still works while hidden. Saved boolean, on by default.'],
  panic_outside_seconds:['Panic appearance delay','Continuous seconds outside before Panic appears. Overheating reveals it immediately. Default 3; range 0–30. Session only.'],
  panic_cooldown_seconds:['Panic cooldown','Seconds of play between rescues. Pause/Help freeze it; new level or retry resets it. Default 30; range 0–300. Session only.'],
  panic_score_penalty_percent:['Panic score penalty percent','Percent of the current run score deducted once per successful rescue when panic_penalty is on, rounded to nearest whole points. All-time records are unchanged. Default 5; range 0–100. Session only.'],
  damage:['Damage','Allow normal-level cell damage from boundaries and laser grids, including shutters.'],
  mercy_mode:['Critical damage grace','Quiet, default-on protection when two damaging hits within mercy_damage_window_seconds leave at most mercy_cube_threshold cubes. Ordinary hazards only; no announcement or restored cells. Session only.'],
  mercy_seconds:['Mercy protection duration','Seconds without laser, shutter or boundary damage after a qualifying burst. Default 1.5; range 0–10. 0 disables new grace windows. Applies on the next trigger; session only.'],
  mercy_cube_threshold:['Mercy surviving cube threshold','Maximum cubes left after the triggering hit. Default 20; integer 1–125. Low count alone does not activate protection. Session only.'],
  mercy_damage_window_seconds:['Mercy rapid damage window','Maximum seconds between two real damaging hits to qualify as rapid damage. Default 0.5; range 0–5. Blocked hits do not count. Session only.'],
  mercy_cooldown_seconds:['Mercy cooldown after protection','Seconds of normal play after grace ends before another burst can trigger it. Default 15; range 0–300. Hits and toggles cannot reset it; applies on the next trigger. Session only.'],
  lasers:['Laser grids','Enable laser hazards, including electric shutters.'],
  bounds:['Boundary damage','Allow corridor boundaries to shave off exposed cells and trigger overheating.'],
  noclip:['Free boundary movement','Bypass corridor boundary damage, heat and collapsed-leg movement restrictions; laser hazards remain active.'],
  portal:['Portal activation','Allow the exit portal to absorb cells and finish the level.'],
  suction:['Portal suction','Pull the player body toward an active exit portal.'],
  route3d:['Three-dimensional routes','Introduce world-Y route segments from SPACE onward; changing this rebuilds the current route.'],
  shake:['Shaking and heat flashes','Show player heat tremors, heat flashes, bonus warning tremors and camera jolts.'],
  spin:['Player auto-rotation','Slowly tumble the surviving body across X/Y/Z in normal levels; rotated cells affect collision.'],
  rotation_shocks:['Hit rotation shocks','Apply a brief visual rotational recoil when the body takes a hit.'],
  portal_white_light:['Portal white light','Show a white halo that strengthens near the portal.'],
  end_portal:['Final white portal','Give the level-cap exit an oversized pure-white frame and glow. Saved visual flag; portal_white_light controls its halo. Capture and suction stay unchanged.'],
  culling:['Cull distant corridors','Limit rendered corridor detail; disabling this does not reveal or arm distant laser hazards.'],
  microgravity:['Microgravity propulsion','Use thrust, coasting and braking in normal levels; off restores direct movement.'],
  overheat_blocks_recoupling:['Overheating blocks re-coupling','Reject new re-coupling requests while hot once the configured HEAT level gate is satisfied.'],
  change_1:['CHANGE 1: electric shutters','Master shutter switch. One-gate sequences start at level 4 by default.'],
  change_2:['CHANGE 2: two-zap sequences','Allow two different gates per sequence from change_2_min_level (default 6).'],
  change_3:['CHANGE 3: three-zap sequences','Allow three different gates per sequence from change_3_min_level (default 7).'],
  change_4:['CHANGE 4: four-zap sequences','Allow four different gates per sequence from change_4_min_level (default 8).'],
  change_4_pattern:['Four-gate pattern','Use mirrored inner, far end, opposite end, other inner order. The exact centre grid is omitted. False randomizes all four selections.'],
  change_1_random_per_leg:['Random shutter gates and legs','Randomize sequence gates and leg selection, or the starting side of the four-gate pattern. Off uses fixed ordering.'],
  change_1_no_repeat_leg:['Alternate sequence legs','After a complete sequence, wait for another nearby revealed leg. All steps inside one sequence remain in the same leg.'],
  change_1_min_level:['First shutter level','Default 4. Master threshold; 0 means level 1. Later stages cannot start before this.'],
  change_2_min_level:['Two-zap introduction level','Default 6. 0 removes this stage threshold; the master shutter threshold still applies.'],
  change_3_min_level:['Three-zap introduction level','Default 7. 0 removes this stage threshold; the master shutter threshold still applies.'],
  change_4_min_level:['Four-zap introduction level','Default 8. 0 removes this stage threshold; the master shutter threshold still applies.'],
  change_1_interval:['Between-sequence spacing','Minimum seconds between the last zap start and the next sequence’s first zap start; default 4. Open-rest settings can extend it.'],
  change_1_step_seconds:['Within-sequence zap spacing','Seconds between consecutive zap starts in the same sequence; default 2. Open-rest settings can extend it.'],
  change_1_closed_seconds:['Shutter closed duration','Seconds fully closed per step, 0.05–30; default 0.8.'],
  change_1_warning_seconds:['Shutter warning duration','Seconds of amber warning before each closure, 0–10; default 0.4.'],
  change_1_damage_fraction:['Shutter damage fraction','Fraction of remaining cells lost on contact, 0–1; rounds down and preserves the last cell.'],
  change_1_gates_per_leg:['Sequence length override','0 uses the 4/6/7/8 level stages. 1–5 forces that many distinct gates, still one at a time.'],
  change_1_gate_cooldown:['Open rest between gates','Minimum seconds after reopening before the next warning; default 0.8. Extends zap spacing when needed.'],
  change_1_damage_cooldown:['Grid damage cooldown','Seconds of protection from all laser grids after a shutter hit; default 1.5.'],
  change_1_pitch_1:['Zap 1 pitch','Semitones relative to the original electric sound; default +0. Applies to closing and reopening. Range -12 to 12.'],
  change_1_pitch_2:['Zap 2 pitch','Semitones relative to the original electric sound; default -3. Applies to closing and reopening. Range -12 to 12.'],
  change_1_pitch_3:['Zap 3 pitch','Semitones relative to the original electric sound; default +3. Applies to closing and reopening. Range -12 to 12.'],
  change_1_pitch_4:['Zap 4 pitch','Semitones relative to the original electric sound; default +7. Applies to closing and reopening. Range -12 to 12.'],
  change_1_pitch_5:['Zap 5 pitch','Semitones relative to the original electric sound; default -7. Applies to closing and reopening. Range -12 to 12.'],
  auto_locate_min_level:['Automatic camera tracking level','Follow the player at or above this level; 0 means always on. Integer 0–1000000; intro overviews remain.'],
  loss:['Permanent portal loss','From loss_min_level, exits carry the surviving body into the next level. Retries restore the level-entry body; bonuses do not refill it. Saved boolean.'],
  loss_grey:['LOSS colour fading','Subtle colour loss at loss_grey_min_level, accelerating nonlinearly to full grey at the level cap. Visual only; heat flashes remain. Saved boolean.'],
  loss_min_level:['LOSS starting level','First level whose exit stops refilling the body; default 16 in mode 20, 44 in mode 50. Integer 0 to the active cap; 0 starts at level 1. Moves the LOSS banner. Session only.'],
  loss_grey_min_level:['Colour fade starting level','Start barely perceptible colour loss here, then fade quadratically to full grey at the active cap. Default 10 in mode 20, 44 in mode 50. 0 starts at level 1. Independent of LOSS. Session only.'],
  route_outline:['Upcoming corridor outlines','Show faint exterior edges ahead during normal play without revealing distant hazards. Saved boolean; independent of the opening preview.'],
  route_outline_ahead_legs:['Upcoming outline distance','Number of legs ahead to outline during play, default 5. 0 hides them. Session only; does not reveal hazards.'],
  route_outline_fade_after_legs:['Upcoming outline fade starts after','Keep this many upcoming legs at full outline opacity, then fade with distance; default 1.'],
  route_outline_opacity:['Upcoming outline brightness','Near opacity during play, 0–1; default 0.32.'],
  route_outline_far_opacity:['Upcoming far outline fraction','Fraction of near opacity at the far end, 0–1; default 0.25.'],
  preview_outline:['Ghost route preview','Show four exterior corridor edges in the opening overview; gates stay hidden. Saved boolean.'],
  preview_max_legs:['Maximum preview legs','Limit the opening ghost outline to this many legs; 0 hides it. Default 50; session only. The camera and portal still frame the full route.'],
  preview_fade_after_legs:['Preview fade starts after','Keep this many near legs at full preview opacity, then fade gradually toward the end; default 2.'],
  preview_opacity:['Near preview opacity','Ghost outline opacity from 0 to 1; default 0.24.'],
  preview_far_opacity:['Far preview opacity fraction','Fraction of near opacity remaining at the far end, 0–1; default 0.12.'],
  star_pattern:['Background star pattern','0: no background stars; 1: original evenly spaced sky; 2: irregular stars with varied sizes, brightness and subtle hues.'],
  locate:['Manual camera tracking','Force the camera to follow the player; turning this off still allows automatic tracking.'],
  mute:['Mute audio','Silence music and sound effects.'],
  controller:['Controller input','Enable standard Xbox-style gamepads. Keyboard and touch controls remain available.'],
  controller_deadzone:['Controller stick deadzone','Ignore small stick deflections to prevent drift; range 0–0.8, default 0.18. Saved in this browser.'],
  mobile_mode:['Mobile input mode','0 automatic, 1 touch beta, 2 keyboard/controller. Saved in this browser; game rules are unchanged.'],
  touch_helpers:['Extra touch areas','Show optional drag/depth thumb areas alongside the cube orb. Saved boolean, off by default.'],
  touch_rush_radius:['Touch rush threshold','Distance from the initial touch to engage rush, in CSS pixels; 38–140, default 56. Session only.'],
  touch_deadzone:['Touch motion deadzone','Ignore small finger motion in CSS pixels; 0–24, default 6. Session only.'],
  touch_grab_radius:['Minimum cube grab radius','Minimum size of the cube touch region in CSS pixels; 24–100, default 44. Session only.'],
  mobile_pixel_ratio:['Touch drawing resolution','Maximum drawing pixels per CSS pixel in touch mode; 0.5–2, default 1.25. Session only.'],
  level:['Current level','Start a fresh full body and show applicable milestone cards with level N or set level N; the current campaign cap is 50.'],
  top_level:['Saved top level','Highest level reached in this browser across runs. Query: toplevel / top_level. Reset to 1: toplevel reset / top_level reset / reset top level.'],
  score:['Run score','Set the current score with score N; non-negative whole number.'],
  cubes:['Surviving cells','Set the surviving cell count with cubes N, from 0 to 125.'],
});

export function describeConsoleConfig(settings,values) {
  const registry=new Map([...settings,...[...values].map(([key,get])=>[key,{get}])]);
  const rows=[...registry].sort(([a],[b])=>a.localeCompare(b)).map(([key,setting])=>{
    const value=setting.get();
    const details=Object.hasOwn(DETAILS,key)?DETAILS[key]:[];
    const name=setting.name||details[0]||key.replaceAll('_',' ').replace(/^./,s=>s.toUpperCase());
    const description=setting.description||details[1]||`${typeof value==='boolean'?'Enable or disable':'Set'} ${name.toLowerCase()}.`;
    return `${key} | ${value} | ${name} | ${description}`;
  });
  return ['CONFIGURATION · CURRENT VALUES','Parameter | Value | Friendly name | Description',...rows,'',
    `${rows.length} parameters. Scroll with the mouse wheel or Page Up / Page Down.`,
    'Query: status <name> · Change: set <name> <value> (score/cubes: score N / cubes N; top_level: toplevel reset)',
    'Booleans: toggle <name>, or true/false, on/off, 1/0, enabled/disabled.'].join('\n');
}
